package slapp.editor.free_form;

public enum ElementTypes {
    SIMPLE_EDIT,
    TRUTH_TABLE,
    HORIZ_TREE,
    VERT_TREE_BASE_ITAL,
    VERT_TREE_ITAL_SANS,
    N_DERIVATION_ITAL_SANS,
    N_DERIVATION_SCIRPT_SANS,
    N_DERIVATION_ITAL_BB,
    A_DERIVATION_ITAL_SANS,
    A_DERIVATION_SCRIPT_SANS,
    A_DERIVATION_ITAL_BB

}
